name: Application Check

on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: Application Check
      run: echo "Hello Application Check!!!"
    - name: ブランチ名
      run: echo "${GITHUB_HEAD_REF}"
