name: Application Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    if: ${{ github.head_ref != 'develop' || github.base_ref != 'staging' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: ブランチ名表示
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
      - name: develop->staging 以外実行
        run: echo "Hello World"
