name: Application Check

on:
  pull_request:
    branches-ignore:
      - 'staging'

jobs:
  application-check:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello World!!!"
