name: Application Check

on:
  pull_request:
    branches-ignore:
      - 'staging'

jobs:
  application-check:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello World!!!"
      - name: PR番号
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: ブランチ名
        run: echo "${GITHUB_HEAD_REF}"
      - name: ブランチ名
        run: echo "${{ github.ref }}"
