name: Application Check

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: ブランチ名
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
      - name: local->staging 以外実行
        run: echo "World"
        if: ${{ github.head_ref != 'local' || github.base_ref != 'staging' }}
