name: Application Check

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo called!
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.base_ref }}"
