name: Application Check

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "World"
        if: ${{ github.head_ref == 'local' && github.base_ref == 'staging' }}
