name: Testing Production

on:
  pull_request:
    branches:
      - production

jobs:
  testing-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: echo "Hello World!!!"
      - uses: ./.github/workflows/application-check.yml
