name: Testing Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  testing-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: echo "Hello World!!!"
      - uses: ./.github/workflows/application-check.yml
