name: Testing Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  testing-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: echo "Hello World!!!"
      - uses: ./.github/workflows/application-check.yml
