name: Testing Local

on:
  pull_request:
    branches:
      - local

jobs:
  testing-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: ls -al /home/runner/work/github-workflow-sample/github-workflow-sample
      - uses: ./.github/workflows/application-check.yml
